// src/lib/components/SpritePet.svelte
<script lang="ts">
  import {
    fpsFor,
    loopRestMsFor,
    animationFor,
    type CodexPet,
    type CodexPetState,
  } from '../utils/codex-pet';

  interface Props {
    pet: CodexPet;
    state: CodexPetState;
    size: number;
    loop?: boolean;
    onOneShotEnd?: () => void;
    class?: string;
    style?: string;
  }

  let {
    pet,
    state: currentState,
    size,
    loop: loopAnim = false,
    onOneShotEnd,
    class: className = '',
    style = '',
  }: Props = $props();

  let spriteEl: HTMLDivElement | undefined = $state();

  const row = $derived(animationFor(pet, currentState) ?? animationFor(pet, 'idle'));
  const aspect = $derived(pet.atlas.cellH / pet.atlas.cellW);
  const renderW = $derived(Math.max(1, Math.round(size)));
  const renderH = $derived(Math.max(1, Math.round(size * aspect)));
  const totalW = $derived(renderW * pet.atlas.cols);
  const totalH = $derived(renderH * pet.atlas.rows);
  const rowScale = $derived(row?.displayScale ?? 1);
  const transform = $derived.by(() => {
    const parts: string[] = [];
    if (row?.flipX) parts.push('scaleX(-1)');
    if (rowScale !== 1) parts.push(`scale(${rowScale})`);
    return parts.length ? parts.join(' ') : undefined;
  });

  $effect(() => {
    const state = currentState;
    const curPet = pet;
    const el = spriteEl;
    if (!el) return;

    let frameIndex = 0;
    let restUntil = 0;
    let oneShotFired = false;
    let acc = 0;
    let last = performance.now();
    let raf: number;
    let cancelled = false;

    function tick(now: number) {
      if (cancelled) return;

      if (restUntil > 0) {
        if (now < restUntil) {
          last = now;
          acc = 0;
          raf = requestAnimationFrame(tick);
          return;
        }
        restUntil = 0;
        frameIndex = 0;
        last = now;
        acc = 0;
        raf = requestAnimationFrame(tick);
        return;
      }

      const fps = fpsFor(curPet, state);
      const frameMs = 1000 / fps;
      const dt = now - last;
      last = now;
      acc = Math.min(acc + dt, frameMs * 1.5);

      while (acc >= frameMs) {
        if (restUntil > 0) break;
        acc -= frameMs;

        const curRow = animationFor(curPet, state) ?? animationFor(curPet, 'idle');
        if (!curRow) continue;

        const next = frameIndex + 1;
        const isOneShot = curPet.oneShot.has(state);

        if (isOneShot && !loopAnim) {
          if (next >= curRow.frames) {
            if (!oneShotFired) {
              oneShotFired = true;
              onOneShotEnd?.();
            }
            frameIndex = curRow.frames - 1;
          } else {
            frameIndex = next;
          }
        } else {
          if (next >= curRow.frames) {
            const restMs = loopRestMsFor(curPet, state);
            if (restMs > 0) {
              restUntil = now + restMs;
              frameIndex = curRow.frames - 1;
            } else {
              frameIndex = 0;
            }
          } else {
            frameIndex = next;
          }
        }
      }

      const curRow = animationFor(curPet, state) ?? animationFor(curPet, 'idle');
      if (curRow && el) {
        const offsetCol = curRow.offsetCol ?? 0;
        const frame = Math.min(frameIndex, curRow.frames - 1);
        const bgX = -(offsetCol + frame) * renderW;
        const bgY = -curRow.row * renderH;
        el.style.backgroundPosition = `${bgX}px ${bgY}px`;
      }

      raf = requestAnimationFrame(tick);
    }

    // Set initial position immediately so the first frame is correct
    const initRow = animationFor(curPet, state) ?? animationFor(curPet, 'idle');
    if (initRow) {
      const offsetCol = initRow.offsetCol ?? 0;
      el.style.backgroundPosition = `${-(offsetCol) * renderW}px ${-initRow.row * renderH}px`;
    }

    raf = requestAnimationFrame(tick);
    return () => {
      cancelled = true;
      cancelAnimationFrame(raf);
    };
  });
</script>

{#if row}
  <div
    bind:this={spriteEl}
    data-physics-anchor
    class={className}
    style:width="{renderW}px"
    style:height="{renderH}px"
    style:background-image="url({pet.spritesheetUrl})"
    style:background-repeat="no-repeat"
    style:background-size="{totalW}px {totalH}px"
    style:image-rendering={pet.imageRendering}
    style:will-change="background-position"
    style:transform={transform}
    style:transform-origin={rowScale !== 1 ? 'bottom center' : undefined}
    style:overflow="visible"
    {style}
  ></div>
{/if}

// frontend/src/components/SpritePet.tsx
import { useEffect, useRef, useState } from 'react'
import {
  ATLAS,
  ANIMATION_ROWS,
  fpsFor,
  type CodexPet,
  type CodexPetState,
} from '../lib/codexPet'

interface SpritePetProps {
  pet: CodexPet
  state: CodexPetState
  // Visual width in CSS pixels. Height is derived from the 192:208 cell ratio.
  size: number
  // Fired once jumping reaches its last frame so the parent can flip back
  // to its previous resting state. No-op for looping states.
  onOneShotEnd?: () => void
  className?: string
  style?: React.CSSProperties
}

// Render a single 192x208 cell from a hatch-pet style 8x9 atlas, advancing
// frames at SPRITE_FPS via requestAnimationFrame. Looping states cycle
// indefinitely; one-shot states (currently `jumping`) hold the last frame
// and notify the parent via onOneShotEnd.
const ONE_SHOT_STATES: ReadonlySet<CodexPetState> = new Set(['jumping'])

export function SpritePet({ pet, state, size, onOneShotEnd, className, style }: SpritePetProps) {
  const [frameIndex, setFrameIndex] = useState(0)
  const stateRef = useRef(state)
  const onOneShotEndRef = useRef(onOneShotEnd)
  const oneShotFiredRef = useRef(false)

  useEffect(() => {
    stateRef.current = state
    oneShotFiredRef.current = false
    setFrameIndex(0)
  }, [state])

  useEffect(() => {
    onOneShotEndRef.current = onOneShotEnd
  }, [onOneShotEnd])

  useEffect(() => {
    let raf = 0
    let acc = 0
    let last = performance.now()
    let cancelled = false

    const tick = (now: number) => {
      if (cancelled) return
      const dt = now - last
      last = now
      acc += dt
      // Re-read the per-frame interval each iteration so per-state fps
      // overrides (e.g. a slower idle loop) take effect immediately when
      // the state changes mid-tick.
      const frameMs = 1000 / fpsFor(stateRef.current)
      while (acc >= frameMs) {
        acc -= frameMs
        const cur = stateRef.current
        const row = ANIMATION_ROWS[cur]
        if (!row) continue
        setFrameIndex((prev) => {
          const next = prev + 1
          if (ONE_SHOT_STATES.has(cur)) {
            if (next >= row.frames) {
              if (!oneShotFiredRef.current) {
                oneShotFiredRef.current = true
                const cb = onOneShotEndRef.current
                if (cb) queueMicrotask(cb)
              }
              return row.frames - 1
            }
            return next
          }
          return next % row.frames
        })
      }
      raf = requestAnimationFrame(tick)
    }
    raf = requestAnimationFrame(tick)
    return () => {
      cancelled = true
      cancelAnimationFrame(raf)
    }
  }, [])

  const row = ANIMATION_ROWS[state]
  const frame = Math.min(frameIndex, row.frames - 1)
  const aspect = ATLAS.cellH / ATLAS.cellW
  const renderW = size
  const renderH = size * aspect
  const scale = renderW / ATLAS.cellW
  const totalW = ATLAS.cellW * ATLAS.cols * scale
  const totalH = ATLAS.cellH * ATLAS.rows * scale
  const bgX = -frame * ATLAS.cellW * scale
  const bgY = -row.row * ATLAS.cellH * scale

  return (
    <div
      className={className}
      style={{
        width: renderW,
        height: renderH,
        backgroundImage: `url("${pet.spritesheetUrl}")`,
        backgroundRepeat: 'no-repeat',
        backgroundSize: `${totalW}px ${totalH}px`,
        backgroundPosition: `${bgX}px ${bgY}px`,
        imageRendering: 'pixelated',
        ...style,
      }}
    />
  )
}
